name: 'formik-migrate'
description: 'Analyze Formik usage and block PRs that add new Formik code'
author: 'willzhangfly'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  path:
    description: 'Path to the project directory'
    required: false
    default: '.'
  fail-on-formik:
    description: 'Fail if any Formik usage is detected'
    required: false
    default: 'false'
  fail-on-new-formik:
    description: 'Fail if new Formik usage is added (compared to base branch)'
    required: false
    default: 'true'
  max-formik-files:
    description: 'Maximum number of files with Formik before failing'
    required: false
    default: '0'
  comment-on-pr:
    description: 'Add a comment to the PR with the analysis'
    required: false
    default: 'true'

outputs:
  formik-files:
    description: 'Number of files using Formik'
  auto-convertible:
    description: 'Number of patterns that can be auto-converted'
  manual-review:
    description: 'Number of patterns needing manual review'
  has-formik:
    description: 'Whether any Formik usage was detected'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run formik-migrate analysis
      id: analyze
      shell: bash
      run: |
        cd "${{ inputs.path }}"

        # Run analysis and capture JSON output
        npx formik-migrate@latest analyze --format json > /tmp/formik-analysis.json 2>/dev/null || true

        # Extract values using jq (or node if jq not available)
        if command -v jq &> /dev/null; then
          FORMIK_FILES=$(jq -r '.formikFiles // 0' /tmp/formik-analysis.json)
          AUTO_CONVERTIBLE=$(jq -r '.autoConvertible // 0' /tmp/formik-analysis.json)
          MANUAL_REVIEW=$(jq -r '.manualReviewNeeded // 0' /tmp/formik-analysis.json)
        else
          FORMIK_FILES=$(node -e "const d=require('/tmp/formik-analysis.json'); console.log(d.formikFiles || 0)")
          AUTO_CONVERTIBLE=$(node -e "const d=require('/tmp/formik-analysis.json'); console.log(d.autoConvertible || 0)")
          MANUAL_REVIEW=$(node -e "const d=require('/tmp/formik-analysis.json'); console.log(d.manualReviewNeeded || 0)")
        fi

        HAS_FORMIK=$([[ "$FORMIK_FILES" -gt 0 ]] && echo "true" || echo "false")

        echo "formik-files=$FORMIK_FILES" >> $GITHUB_OUTPUT
        echo "auto-convertible=$AUTO_CONVERTIBLE" >> $GITHUB_OUTPUT
        echo "manual-review=$MANUAL_REVIEW" >> $GITHUB_OUTPUT
        echo "has-formik=$HAS_FORMIK" >> $GITHUB_OUTPUT

        # Display results
        echo "📊 Formik Migration Analysis"
        echo "============================"
        echo "Files with Formik: $FORMIK_FILES"
        echo "Auto-convertible:  $AUTO_CONVERTIBLE"
        echo "Manual review:     $MANUAL_REVIEW"

        # Check fail conditions
        if [[ "${{ inputs.fail-on-formik }}" == "true" && "$HAS_FORMIK" == "true" ]]; then
          echo "::error::Formik usage detected. Please migrate to React Hook Form."
          exit 1
        fi

        MAX_FILES="${{ inputs.max-formik-files }}"
        if [[ "$MAX_FILES" -gt 0 && "$FORMIK_FILES" -gt "$MAX_FILES" ]]; then
          echo "::error::Too many files using Formik ($FORMIK_FILES > $MAX_FILES)"
          exit 1
        fi

    - name: Comment on PR
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const formikFiles = '${{ steps.analyze.outputs.formik-files }}';
          const autoConvertible = '${{ steps.analyze.outputs.auto-convertible }}';
          const manualReview = '${{ steps.analyze.outputs.manual-review }}';

          if (formikFiles === '0') {
            console.log('No Formik usage detected, skipping comment');
            return;
          }

          const body = `## 🔄 Formik Migration Analysis

          | Metric | Count |
          |--------|-------|
          | Files with Formik | ${formikFiles} |
          | Auto-convertible | ${autoConvertible} ✅ |
          | Manual review needed | ${manualReview} ⚠️ |

          <details>
          <summary>How to migrate</summary>

          \`\`\`bash
          # Analyze your codebase
          npx formik-migrate analyze

          # Auto-convert simple patterns
          npx formik-migrate convert --backup

          # Install React Hook Form
          npm install react-hook-form @hookform/resolvers
          \`\`\`

          </details>

          ---
          *Generated by [formik-migrate](https://github.com/willzhangfly/formik-migrate)*`;

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existingComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('Formik Migration Analysis')
          );

          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }
